<?php

/**
 * You need to implement hook_migrate_api for custom classes
 * to be picked up by migrate module.
 */
function migrate_json_migrate_api() {
    $api = array(
      'api' => 2,
      'groups' => array(
        'dna' => array(
      	   'title' => t('DNA Group'),
           'default_format' => 'filtered_html',
         ),
       ),
      'migrations' => array(
        'JSON' => array(
          'class_name' => 'JSONMigration',
          'group_name' => 'dna',
         ),
       ),
    );

    return $api;
}

//Hide the age in the user profile.
function migrate_json_user_view_alter(&$build) {
  if (isset($build['field_age'])) {
    unset($build['field_age']);
   }
}
